//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarvelClaimer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarvelClaimer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ct_rpc_action&quot;:&quot;questionnaire_submit&quot;,&quot;answers&quot;:{&quot;2&quot;:{&quot;selected_answers&quot;:[],&quot;response_text&quot;:&quot;30&quot;},&quot;4&quot;:{&quot;selected_answers&quot;:[&quot;2&quot;],&quot;response_text&quot;:null},&quot;5&quot;:{&quot;selected_answers&quot;:[],&quot;response_text&quot;:&quot;20&quot;},&quot;6&quot;:{&quot;selected_answers&quot;:[&quot;3&quot;],&quot;response_text&quot;:null},&quot;7&quot;:{&quot;selected_answers&quot;:[&quot;2&quot;],&quot;response_text&quot;:null},&quot;8&quot;:{&quot;selected_answers&quot;:[&quot;3&quot;],&quot;response_text&quot;:null},&quot;9&quot;:{&quot;selected_answers&quot;:[&quot;4&quot;],&quot;response_text&quot;:null},&quot;10&quot;:{&quot;selected_answers&quot;:[&quot;2&quot;],&quot;response_text&quot;:null},&quot;11&quot;:{&quot;selected_answers&quot;:[&quot;3&quot;],&quot;response_text&quot;:nul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProfileQnaBody {
            get {
                return ResourceManager.GetString("ProfileQnaBody", resourceCulture);
            }
        }
    }
}
