//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarvelClaimer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarvelClaimer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;page_data&quot;:{&quot;text&quot;:[&quot;text.activity widget unlock&quot;,&quot;text.activity widget tier unlock&quot;,&quot;text.bonus&quot;,&quot;text.activity widget available&quot;,&quot;button.go&quot;,&quot;cms.month:january&quot;,&quot;cms.month:february&quot;,&quot;cms.month:march&quot;,&quot;cms.month:april&quot;,&quot;cms.month:may&quot;,&quot;cms.month:june&quot;,&quot;cms.month:july&quot;,&quot;cms.month:august&quot;,&quot;cms.month:september&quot;,&quot;cms.month:october&quot;,&quot;cms.month:november&quot;,&quot;cms.month:december&quot;,&quot;text.points display&quot;,&quot;text.point display&quot;,&quot;text.days&quot;,&quot;text.hours&quot;,&quot;text.minutes&quot;,&quot;text.seconds&quot;,&quot;error.unknown&quot;,&quot;button.submit&quot;]},&quot;mode [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComicsActivitiesBody {
            get {
                return ResourceManager.GetString("ComicsActivitiesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;page_data&quot;:{&quot;text&quot;:[&quot;text.activity widget unlock&quot;,&quot;text.activity widget tier unlock&quot;,&quot;text.bonus&quot;,&quot;text.activity widget available&quot;,&quot;button.go&quot;,&quot;cms.month:january&quot;,&quot;cms.month:february&quot;,&quot;cms.month:march&quot;,&quot;cms.month:april&quot;,&quot;cms.month:may&quot;,&quot;cms.month:june&quot;,&quot;cms.month:july&quot;,&quot;cms.month:august&quot;,&quot;cms.month:september&quot;,&quot;cms.month:october&quot;,&quot;cms.month:november&quot;,&quot;cms.month:december&quot;,&quot;text.points display&quot;,&quot;text.point display&quot;,&quot;text.days&quot;,&quot;text.hours&quot;,&quot;text.minutes&quot;,&quot;text.seconds&quot;,&quot;error.unknown&quot;,&quot;button.submit&quot;]},&quot;mode [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GamesActivitiesBody {
            get {
                return ResourceManager.GetString("GamesActivitiesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ct_rpc_action&quot;:&quot;questionnaire_submit&quot;,&quot;answers&quot;:{&quot;1&quot;:{&quot;selected_answers&quot;:[&quot;1&quot;],&quot;response_text&quot;:null},&quot;2&quot;:{&quot;selected_answers&quot;:[&quot;3&quot;],&quot;response_text&quot;:null},&quot;3&quot;:{&quot;selected_answers&quot;:[&quot;3&quot;],&quot;response_text&quot;:null},&quot;4&quot;:{&quot;selected_answers&quot;:[&quot;3&quot;],&quot;response_text&quot;:null},&quot;5&quot;:{&quot;selected_answers&quot;:[&quot;3&quot;],&quot;response_text&quot;:null},&quot;6&quot;:{&quot;selected_answers&quot;:[&quot;2&quot;],&quot;response_text&quot;:null}},&quot;questionnaire_id&quot;:&quot;d3c4411f-0a9d-479a-8d47-a082f650e793&quot;,&quot;questionnaire_type&quot;:&quot;quiz&quot;}.
        /// </summary>
        internal static string JudgementQnaBody {
            get {
                return ResourceManager.GetString("JudgementQnaBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;page_data&quot;:{&quot;text&quot;:[&quot;text.activity widget unlock&quot;,&quot;text.activity widget tier unlock&quot;,&quot;text.bonus&quot;,&quot;text.activity widget available&quot;,&quot;button.go&quot;,&quot;cms.month:january&quot;,&quot;cms.month:february&quot;,&quot;cms.month:march&quot;,&quot;cms.month:april&quot;,&quot;cms.month:may&quot;,&quot;cms.month:june&quot;,&quot;cms.month:july&quot;,&quot;cms.month:august&quot;,&quot;cms.month:september&quot;,&quot;cms.month:october&quot;,&quot;cms.month:november&quot;,&quot;cms.month:december&quot;,&quot;text.points display&quot;,&quot;text.point display&quot;,&quot;text.days&quot;,&quot;text.hours&quot;,&quot;text.minutes&quot;,&quot;text.seconds&quot;,&quot;error.unknown&quot;,&quot;button.submit&quot;]},&quot;mode [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LatestActivitiesBody {
            get {
                return ResourceManager.GetString("LatestActivitiesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ct_rpc_action&quot;:&quot;questionnaire_submit&quot;,&quot;answers&quot;:{&quot;1&quot;:{&quot;selected_answers&quot;:[&quot;1&quot;],&quot;response_text&quot;:null}},&quot;questionnaire_id&quot;:&quot;d73684fd-5b79-4a92-bfe6-3c154301e1b6&quot;,&quot;questionnaire_type&quot;:&quot;survey&quot;}.
        /// </summary>
        internal static string MonsterQnaBody {
            get {
                return ResourceManager.GetString("MonsterQnaBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ct_rpc_action&quot;:&quot;questionnaire_submit&quot;,&quot;answers&quot;:{&quot;1&quot;:{&quot;selected_answers&quot;:[&quot;1&quot;],&quot;response_text&quot;:null},&quot;2&quot;:{&quot;selected_answers&quot;:[&quot;1&quot;],&quot;response_text&quot;:null},&quot;3&quot;:{&quot;selected_answers&quot;:[&quot;1&quot;],&quot;response_text&quot;:null},&quot;4&quot;:{&quot;selected_answers&quot;:[&quot;1&quot;],&quot;response_text&quot;:null},&quot;5&quot;:{&quot;selected_answers&quot;:[&quot;1&quot;],&quot;response_text&quot;:null},&quot;6&quot;:{&quot;selected_answers&quot;:[&quot;1&quot;],&quot;response_text&quot;:null},&quot;7&quot;:{&quot;selected_answers&quot;:[&quot;1&quot;],&quot;response_text&quot;:null}},&quot;questionnaire_id&quot;:&quot;ea6dd091-4d42-4981-9d32-6c4eeb48e164&quot;,&quot;questionnaire_type&quot;:&quot;survey&quot;}.
        /// </summary>
        internal static string NftQnaBody {
            get {
                return ResourceManager.GetString("NftQnaBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ct_rpc_action&quot;:&quot;questionnaire_submit&quot;,&quot;answers&quot;:{&quot;2&quot;:{&quot;selected_answers&quot;:[],&quot;response_text&quot;:&quot;30&quot;},&quot;4&quot;:{&quot;selected_answers&quot;:[&quot;2&quot;],&quot;response_text&quot;:null},&quot;5&quot;:{&quot;selected_answers&quot;:[],&quot;response_text&quot;:&quot;20&quot;},&quot;6&quot;:{&quot;selected_answers&quot;:[&quot;3&quot;],&quot;response_text&quot;:null},&quot;7&quot;:{&quot;selected_answers&quot;:[&quot;2&quot;],&quot;response_text&quot;:null},&quot;8&quot;:{&quot;selected_answers&quot;:[&quot;3&quot;],&quot;response_text&quot;:null},&quot;9&quot;:{&quot;selected_answers&quot;:[&quot;4&quot;],&quot;response_text&quot;:null},&quot;10&quot;:{&quot;selected_answers&quot;:[&quot;2&quot;],&quot;response_text&quot;:null},&quot;11&quot;:{&quot;selected_answers&quot;:[&quot;3&quot;],&quot;response_text&quot;:nul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProfileQnaBody {
            get {
                return ResourceManager.GetString("ProfileQnaBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;page_data&quot;:{&quot;text&quot;:[&quot;heading.invite using link&quot;,&quot;success.invite friends&quot;,&quot;text.explain earn points when invites join&quot;,&quot;text.explain invite points earning 2&quot;,&quot;text.explain referral link&quot;,&quot;text.points earned&quot;,&quot;text.twitter invite friends default tweet&quot;,&quot;title.share on facebook&quot;,&quot;title.share on twitter&quot;,&quot;word.share&quot;,&quot;cms.month:january&quot;,&quot;cms.month:february&quot;,&quot;cms.month:march&quot;,&quot;cms.month:april&quot;,&quot;cms.month:may&quot;,&quot;cms.month:june&quot;,&quot;cms.month:july&quot;,&quot;cms.month:august&quot;,&quot;cms.month:september&quot;,&quot;cms.month:october&quot;,&quot;cms.mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReferralBody {
            get {
                return ResourceManager.GetString("ReferralBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ct_rpc_action&quot;:&quot;questionnaire_submit&quot;,&quot;answers&quot;:{&quot;1&quot;:{&quot;selected_answers&quot;:[&quot;1&quot;],&quot;response_text&quot;:null}},&quot;questionnaire_id&quot;:&quot;76f334c6-4afd-4c7d-8ac0-cc0c3adcf60e&quot;,&quot;questionnaire_type&quot;:&quot;survey&quot;}.
        /// </summary>
        internal static string SuperheroQnaBody {
            get {
                return ResourceManager.GetString("SuperheroQnaBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ct_rpc_action&quot;:&quot;questionnaire_submit&quot;,&quot;answers&quot;:{&quot;1&quot;:{&quot;selected_answers&quot;:[&quot;1&quot;],&quot;response_text&quot;:null}},&quot;questionnaire_id&quot;:&quot;9ca0f492-6b91-4bd4-8d2a-8758eaba1c61&quot;,&quot;questionnaire_type&quot;:&quot;survey&quot;}.
        /// </summary>
        internal static string VillainQnaBody {
            get {
                return ResourceManager.GetString("VillainQnaBody", resourceCulture);
            }
        }
    }
}
